server:
  port: 8080
spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ZWhySwag#1

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: info
    com.zwhy.swag.blog: warn